apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ template "name" . }}"
data:
  database.adapter: {{ .Values.database.adapter | quote }}
  database.username: {{ .Values.database.username | quote }}
  database.password: {{ .Values.database.password | quote }}
  database.host: {{ .Values.database.host | quote }}
  database.name: {{ .Values.database.name | quote }}
