apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
{{ toYaml .Values.codecov.config | indent 4 }}
