apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-workers
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.workers }}
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 15%
  template:
    metadata:
      namespace: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/codecov", "worker", "--config", "/codecov-config/config.yaml"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-file
              mountPath: /codecov-config/
          ports:
            - containerPort: {{ .Values.service.internalPort }}
        {{- if .Values.resources.workers }}
          resources:
{{ toYaml .Values.resources.workers | indent 12 }}
        {{- end}}
      volumes:
        - name: config-file
          configMap:
            name: config
            items:
              - key: config.yaml
                path: config.yaml
